# Generated by Django 5.0.1 on 2024-02-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ctask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ctasktitle', models.TextField(max_length=40)),
                ('Ctaskdesc', models.CharField(max_length=500)),
            ],
        ),
    ]
